### ISSUE TITLE
Agario clone

### ISSUE THREAD

**Issue by rwb99** [huytd/pomoday-v2#68]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/gulp-nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/var/www/html5/agario/agar.io-clone/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/var/www/html5/agario/agar.io-clone/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/var/www/html5/agario/agar.io-clone/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)

fsevents is being cancer

everything new

**Comment by huytd** [comment]
Sorry, look like you created an issue in a wrong repo.

**Comment by rwb99** [comment]
you should private the agario clone repo if your not gonna support it.
